version: '3.5'

services:
  api01: &api_servers
    image: limaenz/rinhabackend-q1-dotnet:27022024
    hostname: api01
    container_name: api01_rinha
    environment:
      - ASPNETCORE_URLS=http://*:9999
      - Connection_String=Host=db;Username=admin;Password=123;Database=rinhaDB;Minimum Pool Size=10;Maximum Pool Size=10;Multiplexing=true;Application Name=RinhaBackEndDB
    depends_on:
      - db
    volumes:
      - ../config:/app/config
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "50MB"

  api02:
    <<: *api_servers
    hostname: api02
    container_name: api02_rinha

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinhaDB
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "440MB"

networks:
  default:
    driver: bridge
    name: rinha-backend-q1-nginx-dotnet