version: '3.5'

services:
  api01:
    image: your_api_image:latest
    hostname: api01
    ports:
      - "5001:80"
    depends_on:
      - db

  api02:
    <<: *api
    hostname: api02
    ports:
      - "5002:80"

  db:
    image: sqlite:latest
    hostname: db
    volumes:
      - ./sql-scripts:/docker-entrypoint-init.sql

  nginx:
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api01
      - api02

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1